# Generated by Django 4.2.3 on 2023-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borad_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
