# Generated by Django 4.2.3 on 2023-07-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notice_Board', '0002_rename_borad_list_board_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board_list',
            old_name='todo',
            new_name='board',
        ),
    ]
